default:
		chmod 755 deployCDN  
		chmod 755 dnsserver.py  
		chmod 755 httpserver     
		chmod 755 stopCDN
		chmod 755 dnsserver
		chmod 755 hosts.txt
		chmod 755 httpserver.py
		chmod 755 runCDN
		chmod 755 testme.txt
